### ISSUE TITLE
呜呜呜

### ISSUE THREAD

**Issue by sunny0130** [starryskyhk/yjxt_demo#2]
好哥哥方便给个数据库么，学习用，不商用！！！

**Comment by starryskyhk** [comment]
这个预警系统是当时最开始最开始的，不太完善，我不确定现在的数据库能否使用，我给你一个数据库的表结构文件吧，不包括数据，数据你自己加下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 中午11:19
收件人:&nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[starryskyhk/yjxt_demo] 呜呜呜 (#2)





 
好哥哥方便给个数据库么，学习用，不商用！！！

**Comment by sunny0130** [comment]
好快啊






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 中午11:22
收件人:&nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&gt;;
抄送:&nbsp;"宁公子"<1462794003@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2)





 这个预警系统是当时最开始最开始的，不太完善，我不确定现在的数据库能否使用，我给你一个数据库的表结构文件吧，不包括数据，数据你自己加下 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年9月25日(星期五) 中午11:19 
 收件人:&amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[starryskyhk/yjxt_demo] 呜呜呜 (#2) 
 
 
 
 
 
   
 好哥哥方便给个数据库么，学习用，不商用！！！

**Comment by starryskyhk** [comment]
刚好在线，数据库已经更新到github中，你下载吧，不过不确定能否使用，因为这个数据库是适配我们开发的最新的学业预警系统的，最新版的我设置的私有仓库


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 中午11:23
收件人:&nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&gt;;
抄送:&nbsp;"Starry_sky"<1545731887@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2)





 好快啊 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年9月25日(星期五) 中午11:22 
 收件人:&amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"宁公子"<1462794003@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2) 
 
 
 
 
 
  这个预警系统是当时最开始最开始的，不太完善，我不确定现在的数据库能否使用，我给你一个数据库的表结构文件吧，不包括数据，数据你自己加下  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年9月25日(星期五) 中午11:19  
  收件人:&amp;amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[starryskyhk/yjxt_demo] 呜呜呜 (#2)  
   
   
   
   
   
     
  好哥哥方便给个数据库么，学习用，不商用！！！

**Comment by sunny0130** [comment]
那 、、、、那最新的不方便开源是么？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 中午11:24
收件人:&nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&gt;;
抄送:&nbsp;"宁公子"<1462794003@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2)





 刚好在线，数据库已经更新到github中，你下载吧，不过不确定能否使用，因为这个数据库是适配我们开发的最新的学业预警系统的，最新版的我设置的私有仓库 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年9月25日(星期五) 中午11:23 
 收件人:&amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Starry_sky"<1545731887@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2) 
 
 
 
 
 
  好快啊  
   
   
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年9月25日(星期五) 中午11:22  
  收件人:&amp;amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"宁公子"<1462794003@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2)  
   
   
   
   
   
   这个预警系统是当时最开始最开始的，不太完善，我不确定现在的数据库能否使用，我给你一个数据库的表结构文件吧，不包括数据，数据你自己加下   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年9月25日(星期五) 中午11:19   
   收件人:&amp;amp;amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;[starryskyhk/yjxt_demo] 呜呜呜 (#2)   
     
     
     
     
     
       
   好哥哥方便给个数据库么，学习用，不商用！！！

**Comment by starryskyhk** [comment]
嗯嗯，对的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 中午11:26
收件人:&nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&gt;;
抄送:&nbsp;"Starry_sky"<1545731887@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2)





 那 、、、、那最新的不方便开源是么？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年9月25日(星期五) 中午11:24 
 收件人:&amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"宁公子"<1462794003@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2) 
 
 
 
 
 
  刚好在线，数据库已经更新到github中，你下载吧，不过不确定能否使用，因为这个数据库是适配我们开发的最新的学业预警系统的，最新版的我设置的私有仓库  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年9月25日(星期五) 中午11:23  
  收件人:&amp;amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"Starry_sky"<1545731887@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2)  
   
   
   
   
   
   好快啊   
     
     
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年9月25日(星期五) 中午11:22   
   收件人:&amp;amp;amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"宁公子"<1462794003@qq.com&amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2)   
     
     
     
     
     
    这个预警系统是当时最开始最开始的，不太完善，我不确定现在的数据库能否使用，我给你一个数据库的表结构文件吧，不包括数据，数据你自己加下    
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2020年9月25日(星期五) 中午11:19    
    收件人:&amp;amp;amp;amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;amp;amp;amp;gt;;    
    抄送:&amp;amp;amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;[starryskyhk/yjxt_demo] 呜呜呜 (#2)    
       
       
       
       
       
         
    好哥哥方便给个数据库么，学习用，不商用！！！

**Comment by sunny0130** [comment]
好的，谢谢，麻烦了你了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 中午11:27
收件人:&nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&gt;;
抄送:&nbsp;"宁公子"<1462794003@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2)





 嗯嗯，对的 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年9月25日(星期五) 中午11:26 
 收件人:&amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Starry_sky"<1545731887@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2) 
 
 
 
 
 
  那 、、、、那最新的不方便开源是么？  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年9月25日(星期五) 中午11:24  
  收件人:&amp;amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"宁公子"<1462794003@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2)  
   
   
   
   
   
   刚好在线，数据库已经更新到github中，你下载吧，不过不确定能否使用，因为这个数据库是适配我们开发的最新的学业预警系统的，最新版的我设置的私有仓库   
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年9月25日(星期五) 中午11:23   
   收件人:&amp;amp;amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"Starry_sky"<1545731887@qq.com&amp;amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2)   
     
     
     
     
     
    好快啊    
       
       
       
       
       
       
    ------------------&amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;nbsp;------------------    
    发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;amp;amp;amp;gt;;    
    发送时间:&amp;amp;amp;amp;nbsp;2020年9月25日(星期五) 中午11:22    
    收件人:&amp;amp;amp;amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;amp;amp;amp;gt;;    
    抄送:&amp;amp;amp;amp;nbsp;"宁公子"<1462794003@qq.com&amp;amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;amp;gt;;    
    主题:&amp;amp;amp;amp;nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2)    
       
       
       
       
       
     这个预警系统是当时最开始最开始的，不太完善，我不确定现在的数据库能否使用，我给你一个数据库的表结构文件吧，不包括数据，数据你自己加下     
         
         
     ------------------&amp;amp;amp;amp;amp;nbsp;原始邮件&amp;amp;amp;amp;amp;nbsp;------------------     
     发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;amp;amp;amp;amp;gt;;     
     发送时间:&amp;amp;amp;amp;amp;nbsp;2020年9月25日(星期五) 中午11:19     
     收件人:&amp;amp;amp;amp;amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;amp;amp;amp;amp;gt;;     
     抄送:&amp;amp;amp;amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;amp;amp;amp;gt;;     
     主题:&amp;amp;amp;amp;amp;nbsp;[starryskyhk/yjxt_demo] 呜呜呜 (#2)     
         
         
         
         
         
           
     好哥哥方便给个数据库么，学习用，不商用！！！

**Comment by sunny0130** [comment]
感激不尽！！！谢谢，好人一生平安！！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 中午11:22
收件人:&nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&gt;;
抄送:&nbsp;"宁公子"<1462794003@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2)





 这个预警系统是当时最开始最开始的，不太完善，我不确定现在的数据库能否使用，我给你一个数据库的表结构文件吧，不包括数据，数据你自己加下 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年9月25日(星期五) 中午11:19 
 收件人:&amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[starryskyhk/yjxt_demo] 呜呜呜 (#2) 
 
 
 
 
 
   
 好哥哥方便给个数据库么，学习用，不商用！！！

**Comment by starryskyhk** [comment]
没事没事




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月25日(星期五) 中午11:30
收件人:&nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&gt;;
抄送:&nbsp;"Starry_sky"<1545731887@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2)





 感激不尽！！！谢谢，好人一生平安！！！！ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年9月25日(星期五) 中午11:22 
 收件人:&amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"宁公子"<1462794003@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [starryskyhk/yjxt_demo] 呜呜呜 (#2) 
 
 
 
 
 
  这个预警系统是当时最开始最开始的，不太完善，我不确定现在的数据库能否使用，我给你一个数据库的表结构文件吧，不包括数据，数据你自己加下  
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "starryskyhk/yjxt_demo"                                                                                    <notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年9月25日(星期五) 中午11:19  
  收件人:&amp;amp;nbsp;"starryskyhk/yjxt_demo"<yjxt_demo@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;[starryskyhk/yjxt_demo] 呜呜呜 (#2)  
   
   
   
   
   
     
  好哥哥方便给个数据库么，学习用，不商用！！！
